'use client';
import { Canvas, useFrame } from '@react-three/fiber';
import { useMemo, useRef } from 'react';
import * as THREE from 'three';

type Variant='home'|'projects'|'about'|'stack'|'resume'|'contact';
const colors:Record<Variant,[string,string]>={home:['#1769f3','#ff3149'],projects:['#7c3aed','#ec4899'],about:['#0ea5e9','#14b8a6'],stack:['#4f46e5','#f97316'],resume:['#0f766e','#84cc16'],contact:['#ff3149','#fb7185']};
function Form({variant}:{variant:Variant}){const root=useRef<THREE.Group>(null);const orbit=useRef<THREE.Group>(null);const [a,b]=colors[variant];const points=useMemo(()=>{const v:number[]=[];for(let i=0;i<100;i++){const r=.6+Math.random()*1.4,t=Math.random()*6.28,p=Math.acos(2*Math.random()-1);v.push(r*Math.sin(p)*Math.cos(t),r*Math.cos(p),r*Math.sin(p)*Math.sin(t))}return new Float32Array(v)},[]);useFrame((s,d)=>{if(root.current){root.current.rotation.y+=d*.12;root.current.rotation.y+=(s.pointer.x*.3-root.current.rotation.y)*.018;root.current.rotation.x=s.pointer.y*.12}if(orbit.current)orbit.current.rotation.z-=d*.22});return <group ref={root}><group ref={orbit}><mesh rotation={[.65,.15,.2]}><torusGeometry args={[1.62,.025,8,100]}/><meshBasicMaterial color={a}/></mesh><mesh rotation={[1.5,.4,.5]}><torusGeometry args={[1.12,.014,8,100]}/><meshBasicMaterial color={b}/></mesh></group><mesh><icosahedronGeometry args={[1.02,3]}/><meshBasicMaterial color={a} wireframe transparent opacity={.34}/></mesh><mesh scale={.55}><sphereGeometry args={[1,32,24]}/><meshStandardMaterial color="#fafdff" metalness={.8} roughness={.12}/></mesh><points><bufferGeometry><bufferAttribute attach="attributes-position" args={[points,3]}/></bufferGeometry><pointsMaterial color={b} size={.038} sizeAttenuation/></points><pointLight color={a} intensity={10} position={[2,2,3]}/><pointLight color={b} intensity={6} position={[-3,-1,2]}/></group>}
export default function WebverseScene({variant='home'}:{variant?:Variant}){return <Canvas camera={{position:[0,0,5.4],fov:43}} dpr={[1,1.6]} gl={{alpha:true,antialias:true}}><ambientLight intensity={1.7}/><directionalLight position={[3,4,5]} intensity={2.5}/><Form variant={variant}/></Canvas>}
